import io
from reportlab.lib.pagesizes import letter
from reportlab.pdfgen import canvas

def generate_traffic_pdf(username, day, hour, weather, predicted_vehicles, traffic_level, recommendation):
    buffer = io.BytesIO()
    p = canvas.Canvas(buffer, pagesize=letter)
    
    # Header
    p.setFont("Helvetica-Bold", 18)
    p.drawString(50, 750, "🚦 SMART TRAFFIC SYSTEM - PREDICTION REPORT")
    p.line(50, 740, 550, 740)
    
    # System Details
    p.setFont("Helvetica", 12)
    p.drawString(50, 700, f"Generated By: {username}")
    p.drawString(50, 680, f"Day & Time: {day} at {hour}:00")
    p.drawString(50, 660, f"Weather Condition: {weather}")
    
    p.line(50, 640, 550, 640)
    
    # AI Prediction Results
    p.setFont("Helvetica-Bold", 14)
    p.drawString(50, 600, "AI Model Prediction Analysis:")
    
    p.setFont("Helvetica", 12)
    p.drawString(50, 575, f"Predicted Vehicle Volume: {predicted_vehicles} Vehicles")
    p.drawString(50, 555, f"Traffic Congestion Level: {traffic_level}")
    p.drawString(50, 535, f"Traffic Advisory: {recommendation}")
    
    # Footer
    p.line(50, 100, 550, 100)
    p.setFont("Helvetica-Oblique", 10)
    p.drawString(50, 80, "Confidential - Automated PDF Report generated by AI Traffic Engine.")
    
    p.showPage()
    p.save()
    buffer.seek(0)
    return buffer